#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/registration
#    username: postgres
#    password: DEC(12345678)
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create
#    show-sql: true
#  thymeleaf:
#    encoding: UTF-8
#spring.jpa.properties.hibernate.format_sql: true
